sudo: required
language: node_js
node_js:
- '8'
services:
- docker
before_install:
- cd anchors
script:
- docker run --rm -v "$(pwd):/anchors" holochain/holochain-proto:develop bash -c "cd /anchors; hcdev test"
